ALTER TABLE "user" ALTER COLUMN registered_at TYPE TIMESTAMP, ALTER COLUMN registered_at SET DEFAULT '2025-12-01 18:51:25.722'::timestamp without time zone;
ALTER TABLE test ADD category VARCHAR(13) DEFAULT 'EMOTIONS' NOT NULL;
